/*
 * Nbsf_Management
 *
 * Binding Support Management Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"fmt"
	"encoding/json"
)

// PcfBindingsBindingIdDelete - 
func PcfBindingsBindingIdDelete(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// PcfBindingsGet - 
func PcfBindingsGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func PcfBindingsPost(w http.ResponseWriter, r *http.Request) {
	var pcfBinding PcfBinding

	json.NewDecoder(r.Body).Decode(&pcfBinding)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	if pcfBinding.Dnn != "" {
		w.WriteHeader(http.StatusCreated)
		// fmt.Fprintf(w, "HTTP: 201\n")
		json.NewEncoder(w).Encode(&pcfBinding)
	} else {
	}

	fmt.Printf("pcfBinding: %+v\n", pcfBinding)
	// fmt.Fprintf(w, "Done\n")
}
