/*
 * Nbsf_Management
 *
 * Binding Support Management Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TransportProtocol struct {
}
